version: '3.7'

services:
  api:
    build:
      context: .
      dockerfile: api.Dockerfile
    container_name: poshbot
    restart: always
    env_file:
      - .env
    depends_on:
      - db
    networks:
      - internal

    # Bind volumes to enable hot-reloads.
    # e.g. when a file is changed in this folder, the change is
    # also applied to the same file inside the docker container.
    volumes:
      - ./PoshBot/:/PoshBot/
      - ./poshmark/:/poshmark/
      - /dev/shm:/dev/shm
      - shared_volume:/shared_volume
  db:
    image: postgres:12.0-alpine
    restart: always
    container_name: postgres_poshbot
    environment:
      - POSTGRES_USER=${SQL_USER}
      - POSTGRES_PASSWORD=${SQL_PASSWORD}
      - POSTGRES_DB=${SQL_DATABASE}
    volumes:
      - postgres_db:/var/lib/postgresql/data/
    networks:
      - internal
    ports:
      - 5432:5432

networks:
  internal:

volumes:
  postgres_db:
  shared_volume:
  lpm_data:
