# Generated by Django 4.0.4 on 2022-04-23 19:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="campaign",
            name="delay",
            field=models.SmallIntegerField(default=60),
            preserve_default=False,
        ),
    ]
