# Generated by Django 4.0.8 on 2022-12-23 20:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0007_alter_poshuser_username"),
    ]

    operations = [
        migrations.AlterField(
            model_name="poshuser",
            name="email",
            field=models.EmailField(blank=True, max_length=254),
        ),
    ]
