# Generated by Django 4.0.8 on 2022-12-24 17:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_poshuser_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime_sent', models.DateTimeField(auto_created=True)),
                ('listing_title', models.CharField(max_length=50)),
                ('amount', models.PositiveIntegerField()),
                ('posh_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offers', to='core.poshuser')),
            ],
        ),
    ]
