# Generated by Django 4.0.8 on 2022-12-24 17:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0009_offer"),
    ]

    operations = [
        migrations.AlterField(
            model_name="offer",
            name="datetime_sent",
            field=models.DateTimeField(),
        ),
    ]
