# Generated by Django 4.0.8 on 2022-12-24 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_offer_datetime_sent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poshuser',
            name='header_picture',
            field=models.ImageField(blank=True, null=True, upload_to='header_pictures'),
        ),
        migrations.AlterField(
            model_name='poshuser',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pictures'),
        ),
    ]
