# Generated by Django 4.0.8 on 2022-12-24 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_poshuser_header_picture_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poshuser',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
    ]
