# Generated by Django 4.0.8 on 2022-12-29 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_proxyconnection'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proxyconnection',
            name='proxy_license_uuid',
            field=models.CharField(max_length=255),
        ),
    ]
