# Generated by Django 4.0.8 on 2023-01-03 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_loggroup_logentry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loggroup',
            name='created_date',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
    ]
