# Generated by Django 4.0.8 on 2023-01-03 00:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0022_alter_loggroup_created_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="loggroup",
            name="created_date",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
