# Generated by Django 4.0.8 on 2023-01-04 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_alter_loggroup_created_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='status',
            field=models.CharField(choices=[('1', 'RUNNING'), ('2', 'IDLE'), ('3', 'STOPPED'), ('4', 'STARTING')], default='3', max_length=15),
        ),
    ]
