# Generated by Django 4.0.8 on 2023-01-12 14:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_alter_campaign_mode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logentry',
            name='log_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='log_entries', to='core.loggroup'),
        ),
    ]
