# Generated by Django 4.0.8 on 2023-02-05 22:04

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0028_alter_campaign_status"),
    ]

    operations = [
        migrations.CreateModel(
            name="Device",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("serial", models.CharField(max_length=12, unique=True)),
                ("ip_reset_url", models.URLField()),
            ],
        ),
        migrations.DeleteModel(
            name="ProxyConnection",
        ),
    ]
