# Generated by Django 4.0.8 on 2023-02-06 00:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0031_device_checkout_time_device_is_active"),
    ]

    operations = [
        migrations.AlterField(
            model_name="device",
            name="checkout_time",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
