# Generated by Django 4.0.8 on 2023-02-09 01:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0032_alter_device_checkout_time"),
    ]

    operations = [
        migrations.AddField(
            model_name="poshuser",
            name="app_package",
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
