# Generated by Django 4.0.8 on 2023-02-15 07:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0033_poshuser_app_package"),
    ]

    operations = [
        migrations.CreateModel(
            name="DeletedClone",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("app_name", models.CharField(max_length=50)),
                (
                    "device",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.device"
                    ),
                ),
            ],
        ),
    ]
