# Generated by Django 4.0.8 on 2023-02-18 23:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0034_deletedclone'),
    ]

    operations = [
        migrations.AddField(
            model_name='poshuser',
            name='device',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.device'),
        ),
    ]
