# Generated by Django 4.0.8 on 2023-02-19 01:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0035_poshuser_device"),
    ]

    operations = [
        migrations.CreateModel(
            name="ListedItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("datetime_listed", models.DateTimeField(blank=True, null=True)),
                ("datetime_passed_review", models.DateTimeField(blank=True, null=True)),
                ("datetime_removed", models.DateTimeField(blank=True, null=True)),
                ("datetime_sold", models.DateTimeField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("NOT LISTED", "NOT LISTED"),
                            ("UP", "UP"),
                            ("UNDER REVIEW", "UNDER REVIEW"),
                            ("RESERVED", "RESERVED"),
                            ("SOLD", "SOLD"),
                            ("REMOVED", "REMOVED"),
                        ],
                        default="NOT LISTED",
                        max_length=255,
                    ),
                ),
                (
                    "listing",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.listing"
                    ),
                ),
                (
                    "posh_user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.poshuser"
                    ),
                ),
            ],
        ),
    ]
