# Generated by Django 4.0.8 on 2023-02-20 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0037_listeditem_listing_title_alter_listeditem_listing'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DeletedClone',
        ),
    ]
