# Generated by Django 4.0.8 on 2023-02-23 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0038_delete_deletedclone'),
    ]

    operations = [
        migrations.AddField(
            model_name='poshuser',
            name='clone_created',
            field=models.BooleanField(default=False),
        ),
    ]
