# Generated by Django 4.0.8 on 2023-02-23 19:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0039_poshuser_clone_created'),
    ]

    operations = [
        migrations.RenameField(
            model_name='poshuser',
            old_name='clone_created',
            new_name='clone_installed',
        ),
    ]
