# Generated by Django 4.0.8 on 2023-02-24 05:04

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0041_poshuser_finished_registration"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="loggroup",
            options={"ordering": ["created_date"]},
        ),
    ]
