# Generated by Django 4.0.8 on 2023-02-24 05:39

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0042_alter_loggroup_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="loggroup",
            options={"ordering": ["-created_date"]},
        ),
    ]
