# Generated by Django 4.0.8 on 2023-03-05 20:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0043_alter_loggroup_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="listing",
            name="brand",
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
