# Generated by Django 4.0.8 on 2023-03-09 21:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0044_alter_listing_brand"),
    ]

    operations = [
        migrations.AlterField(
            model_name="listing",
            name="title",
            field=models.CharField(max_length=80),
        ),
    ]
