# Generated by Django 4.0.8 on 2023-03-10 03:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0045_alter_listing_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='listeditem',
            name='time_to_list',
            field=models.DurationField(blank=True, default=datetime.timedelta(0)),
        ),
        migrations.AddField(
            model_name='poshuser',
            name='time_to_finish_registration',
            field=models.DurationField(blank=True, default=datetime.timedelta(0)),
        ),
        migrations.AddField(
            model_name='poshuser',
            name='time_to_install_clone',
            field=models.DurationField(blank=True, default=datetime.timedelta(0)),
        ),
        migrations.AddField(
            model_name='poshuser',
            name='time_to_register',
            field=models.DurationField(blank=True, default=datetime.timedelta(0)),
        ),
    ]
