# Generated by Django 4.0.8 on 2023-03-18 17:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0046_listeditem_time_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="campaign",
            name="queue_status",
            field=models.CharField(default="UNKNOWN", max_length=15),
        ),
    ]
