# Generated by Django 4.0.8 on 2023-03-09 23:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0046_listeditem_time_to_list_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listeditem',
            name='time_to_list',
            field=models.DurationField(blank=True, default=datetime.timedelta(0)),
        ),
        migrations.AlterField(
            model_name='poshuser',
            name='time_to_finish_registration',
            field=models.DurationField(blank=True, default=datetime.timedelta(0)),
        ),
        migrations.AlterField(
            model_name='poshuser',
            name='time_to_install_clone',
            field=models.DurationField(blank=True, default=datetime.timedelta(0)),
        ),
        migrations.AlterField(
            model_name='poshuser',
            name='time_to_register',
            field=models.DurationField(blank=True, default=datetime.timedelta(0)),
        ),
    ]
