# Generated by Django 4.0.8 on 2023-03-09 23:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0047_alter_listeditem_time_to_list_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listeditem',
            name='time_to_list',
        ),
    ]
