# Generated by Django 4.0.8 on 2023-03-09 23:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0048_remove_listeditem_time_to_list'),
    ]

    operations = [
        migrations.AddField(
            model_name='listeditem',
            name='time_to_list',
            field=models.DurationField(blank=True, default=datetime.timedelta(0)),
        ),
    ]
