# Generated by Django 4.0.8 on 2023-03-19 00:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0049_alter_campaign_queue_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="campaign",
            name="status",
            field=models.CharField(
                choices=[
                    ("RUNNING", "RUNNING"),
                    ("IDLE", "IDLE"),
                    ("STOPPED", "STOPPED"),
                    ("STARTING", "STARTING"),
                    ("STOPPING", "STOPPING"),
                    ("PAUSED", "PAUSED"),
                    ("IN QUEUE", "IN QUEUE"),
                ],
                default="STOPPED",
                max_length=15,
            ),
        ),
    ]
