# Generated by Django 4.0.8 on 2023-04-08 20:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0054_campaign_task_pid_campaign_worker_hostname"),
    ]

    operations = [
        migrations.AlterField(
            model_name="campaign",
            name="worker_hostname",
            field=models.CharField(default="N/A", max_length=255),
        ),
    ]
