# Generated by Django 4.0.8 on 2023-04-08 21:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0055_alter_campaign_worker_hostname"),
    ]

    operations = [
        migrations.AddField(
            model_name="campaign",
            name="sigkill_sent",
            field=models.BooleanField(default=False),
        ),
    ]
