# Generated by Django 4.0.8 on 2023-04-10 13:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0056_campaign_sigkill_sent"),
    ]

    operations = [
        migrations.AlterField(
            model_name="campaign",
            name="task_pid",
            field=models.IntegerField(),
        ),
    ]
