# Generated by Django 4.0.8 on 2023-04-10 16:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0057_alter_campaign_task_pid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campaign',
            name='sigkill_sent',
        ),
        migrations.RemoveField(
            model_name='campaign',
            name='task_pid',
        ),
        migrations.RemoveField(
            model_name='campaign',
            name='worker_hostname',
        ),
    ]
