# Generated by Django 4.0.8 on 2023-04-15 16:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0060_remove_poshuser_email_id_remove_poshuser_sales"),
    ]

    operations = [
        migrations.AddField(
            model_name="poshuser",
            name="zipcode",
            field=models.IntegerField(blank=True, default=32810),
            preserve_default=False,
        ),
    ]
