# Generated by Django 4.0.8 on 2023-04-15 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0062_remove_poshuser_zipcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='poshuser',
            name='email_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='poshuser',
            name='email_password',
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
