# Generated by Django 4.0.8 on 2023-04-19 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0063_poshuser_email_id_poshuser_email_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='poshuser',
            name='email_imap_password',
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
