# Generated by Django 4.0.8 on 2023-04-24 14:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0065_listeditem_listed_item_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="ListedItemOffer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("datetime_sent", models.DateTimeField()),
                ("amount", models.PositiveIntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name="listeditem",
            name="status",
            field=models.CharField(
                choices=[
                    ("NOT LISTED", "NOT LISTED"),
                    ("NOT FOR SALE", "NOT FOR SALE"),
                    ("UP", "UP"),
                    ("UNDER REVIEW", "UNDER REVIEW"),
                    ("RESERVED", "RESERVED"),
                    ("SOLD", "SOLD"),
                    ("REMOVED", "REMOVED"),
                ],
                default="NOT LISTED",
                max_length=255,
            ),
        ),
        migrations.DeleteModel(
            name="Offer",
        ),
        migrations.AddField(
            model_name="listeditemoffer",
            name="listed_item",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="offers",
                to="core.listeditem",
            ),
        ),
        migrations.AddField(
            model_name="listeditemoffer",
            name="posh_user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="offers",
                to="core.poshuser",
            ),
        ),
    ]
