# Generated by Django 4.0.8 on 2023-08-20 01:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0068_listeditemreport'),
    ]

    operations = [
        migrations.CreateModel(
            name='ListedItemToReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('listing_title', models.CharField(max_length=50)),
                ('listed_item_id', models.CharField(max_length=255)),
            ],
        ),
        migrations.RemoveField(
            model_name='listeditemreport',
            name='listed_item_id',
        ),
        migrations.RemoveField(
            model_name='listeditemreport',
            name='listing_title',
        ),
        migrations.AddField(
            model_name='listeditemreport',
            name='posh_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.poshuser'),
        ),
        migrations.AddField(
            model_name='listeditemreport',
            name='listed_item_to_report',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.listeditemtoreport'),
        ),
    ]
