# Generated by Django 4.0.8 on 2023-08-20 03:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0069_listeditemtoreport_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="loggroup",
            name="has_error",
            field=models.BooleanField(default=False),
        ),
    ]
