# Generated by Django 4.0.8 on 2023-08-31 14:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0077_user_phone_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="badphrase",
            name="phrase",
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
