# Generated by Django 4.0.8 on 2023-08-31 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0078_alter_badphrase_phrase'),
    ]

    operations = [
        migrations.AddField(
            model_name='listeditem',
            name='datetime_redeemable',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='listeditem',
            name='earnings',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
