# Generated by Django 4.0.8 on 2023-09-12 16:58

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0082_listeditemtoreport_leave_comment_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Proxy',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('checked_out_by', models.UUIDField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('checkout_time', models.DateTimeField(blank=True, null=True)),
                ('hostname', models.CharField(max_length=255)),
                ('port', models.CharField(max_length=255)),
                ('username', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
                ('license_id', models.CharField(max_length=255)),
            ],
        ),
    ]
