# Generated by Django 4.0.8 on 2023-09-12 19:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0083_proxy"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="device",
            name="ip_reset_url",
        ),
        migrations.AddField(
            model_name="device",
            name="proxy",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.SET_NULL, to="core.proxy"
            ),
        ),
    ]
