# Generated by Django 4.0.8 on 2023-10-08 15:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0086_rename_time_to_install_clone_poshuser_time_to_setup_device_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='proxy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.proxy'),
        ),
    ]
