# Generated by Django 4.0.10 on 2023-11-20 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0088_listeditem_datetime_redeemed_alter_listeditem_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='listeditem',
            name='datetime_shipped',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
