# Generated by Django 4.0.10 on 2023-11-23 16:47

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0089_listeditem_datetime_shipped'),
    ]

    operations = [
        migrations.AddField(
            model_name='poshuser',
            name='cookies',
            field=models.FileField(blank=True, null=True, upload_to=core.models.path_and_rename),
        ),
    ]
