# Generated by Django 4.0.10 on 2023-12-13 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0091_alter_listeditem_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='device',
            name='proxy',
        ),
        migrations.RemoveField(
            model_name='poshuser',
            name='ads_id',
        ),
        migrations.RemoveField(
            model_name='poshuser',
            name='android_id',
        ),
        migrations.RemoveField(
            model_name='poshuser',
            name='bluetooth_id',
        ),
        migrations.RemoveField(
            model_name='poshuser',
            name='cookies',
        ),
        migrations.RemoveField(
            model_name='poshuser',
            name='gsf',
        ),
        migrations.RemoveField(
            model_name='poshuser',
            name='hw_serial',
        ),
        migrations.RemoveField(
            model_name='poshuser',
            name='imei1',
        ),
        migrations.RemoveField(
            model_name='poshuser',
            name='imei2',
        ),
        migrations.RemoveField(
            model_name='poshuser',
            name='media_drm',
        ),
        migrations.RemoveField(
            model_name='poshuser',
            name='mobile_number',
        ),
        migrations.RemoveField(
            model_name='poshuser',
            name='sim_serial',
        ),
        migrations.RemoveField(
            model_name='poshuser',
            name='sim_sub_id',
        ),
        migrations.RemoveField(
            model_name='poshuser',
            name='wifi_bssid',
        ),
        migrations.RemoveField(
            model_name='poshuser',
            name='wifi_mac',
        ),
        migrations.RemoveField(
            model_name='poshuser',
            name='wifi_ssid',
        ),
        migrations.AddField(
            model_name='poshuser',
            name='octo_uuid',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='poshuser',
            name='gender',
            field=models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female')], max_length=10),
        ),
        migrations.DeleteModel(
            name='AppData',
        ),
        migrations.DeleteModel(
            name='Device',
        ),
    ]
