# Generated by Django 4.0.10 on 2023-12-22 22:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0093_remove_listeditemtoreport_leave_comment_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='poshuser',
            name='time_to_setup_device',
        ),
    ]
