# Generated by Django 5.0 on 2023-12-26 19:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0094_remove_poshuser_time_to_setup_device"),
    ]

    operations = [
        migrations.AlterField(
            model_name="listing",
            name="listing_price",
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="listing",
            name="lowest_price",
            field=models.PositiveSmallIntegerField(default=250),
        ),
        migrations.AlterField(
            model_name="listing",
            name="original_price",
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
