# Generated by Django 5.0.1 on 2024-01-08 17:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0097_remove_loggroup_campaign_remove_loggroup_posh_user_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="proxy",
            old_name="proxy_uuid",
            new_name="change_ip_url",
        ),
        migrations.RenameField(
            model_name="proxy",
            old_name="license_id",
            new_name="external_id",
        ),
        migrations.AddField(
            model_name="user",
            name="timezone",
            field=models.CharField(
                choices=[
                    ("America/Adak", "America/Adak"),
                    ("America/Anchorage", "America/Anchorage"),
                    ("America/Boise", "America/Boise"),
                    ("America/Chicago", "America/Chicago"),
                    ("America/Denver", "America/Denver"),
                    ("America/Detroit", "America/Detroit"),
                    ("America/Indiana/Indianapolis", "America/Indiana/Indianapolis"),
                    ("America/Indiana/Knox", "America/Indiana/Knox"),
                    ("America/Indiana/Marengo", "America/Indiana/Marengo"),
                    ("America/Indiana/Petersburg", "America/Indiana/Petersburg"),
                    ("America/Indiana/Tell_City", "America/Indiana/Tell_City"),
                    ("America/Indiana/Vevay", "America/Indiana/Vevay"),
                    ("America/Indiana/Vincennes", "America/Indiana/Vincennes"),
                    ("America/Indiana/Winamac", "America/Indiana/Winamac"),
                    ("America/Juneau", "America/Juneau"),
                    ("America/Kentucky/Louisville", "America/Kentucky/Louisville"),
                    ("America/Kentucky/Monticello", "America/Kentucky/Monticello"),
                    ("America/Los_Angeles", "America/Los_Angeles"),
                    ("America/Menominee", "America/Menominee"),
                    ("America/Metlakatla", "America/Metlakatla"),
                    ("America/New_York", "America/New_York"),
                    ("America/Nome", "America/Nome"),
                    ("America/North_Dakota/Beulah", "America/North_Dakota/Beulah"),
                    ("America/North_Dakota/Center", "America/North_Dakota/Center"),
                    (
                        "America/North_Dakota/New_Salem",
                        "America/North_Dakota/New_Salem",
                    ),
                    ("America/Phoenix", "America/Phoenix"),
                    ("America/Sitka", "America/Sitka"),
                    ("America/Yakutat", "America/Yakutat"),
                ],
                default="America/New_York",
                max_length=255,
            ),
        ),
    ]
