# Generated by Django 5.0.1 on 2024-01-09 15:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0099_remove_poshuser_date_added_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="proxy",
            name="type",
            field=models.CharField(
                choices=[("http", "http"), ("socks5", "socks5")],
                default="http",
                max_length=10,
            ),
        ),
    ]
