name: Build and Deploy PR

on:
  issue_comment:
    types: [created]

jobs:
  build_and_deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
      issues: read
      pull-requests: write
      statuses: write
      packages: write

    steps:
      - name: Pull Request Comment Branch
        uses: xt0rted/pull-request-comment-branch@v2.0.0
        id: comment-branch

      - name: Set commit status to pending
        uses: myrotvorets/set-commit-status-action@v2.0.0
        with:
          sha: ${{ steps.comment-branch.outputs.head_sha }}
          status: pending
          description: 'Building...'

      - name: Checkout PR branch
        uses: actions/checkout@v3
        with:
          ref: ${{ steps.comment-branch.outputs.head_ref }}

      - name: Make API request
        run: |
          API_URL="https://api.github.com/installation/repositories"
          RESPONSE=$(curl -sSL -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" $API_URL)
          echo "API Response: $RESPONSE"

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

#      - name: Build and Push Docker image
#        uses: docker/build-push-action@v2
#        with:
#          context: .
#          file: Dockerfile
#          push: true
#          tags: |
#            ghcr.io/${{ github.repository }}/poshbot-api:pr-${{ steps.comment-branch.outputs.head_ref }}

      - name: Update status description
        uses: myrotvorets/set-commit-status-action@v2.0.0
        with:
          sha: ${{ steps.comment-branch.outputs.head_sha }}
          status: pending
          description: 'Deploying...'

      - name: Authenticate with AWS
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::069773459506:role/github-actions
          aws-region: us-east-1

      - name: Deploy
        run: |
          aws s3api list-buckets

      - uses: mshick/add-pr-comment@v2
        with:
          message: |
            Deployment successful details below:
            

      - name: Set final commit status
        uses: myrotvorets/set-commit-status-action@v2.0.0
        if: always()
        with:
          status: ${{ job.status }}
