name: Build and Deploy PR
# test
on:
  issue_comment:
    types: [created]

jobs:
  build_and_deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Get PR branch
        uses: xt0rted/pull-request-comment-branch@v1
        id: comment-branch

      - name: Set latest commit status as pending
        uses: ouzi-dev/commit-status-updater@v2.0.1
        with:
          status: pending

      - name: Checkout PR branch
        uses: actions/checkout@v3
        with:
          ref: ${{ steps.comment-branch.outputs.head_ref }}

      - name: Set branch name as environment variable
        run: echo "BRANCH_NAME=$(git branch --show-current)" >> $GITHUB_ENV

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: Dockerfile
          push: true
          tags: |
            ghcr.io/${{ github.repository }}/poshbot-api:pr-${{ env.BRANCH_NAME }}

      - name: Authenticate with AWS
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::069773459506:role/github-actions
          aws-region: us-east-1

      - name: Deploy
        run: |
          aws s3api list-buckets

      - name: Set job status
        uses: ouzi-dev/commit-status-updater@v2
        with:
          addHoldComment: "true"
          status: "${{ job.status }}"